apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gitlab.gitlab.svc.cluster.local:8082/root/psegura-bonus-iot.git
    targetRevision: HEAD
    path: bonus_manifests/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true