apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/pepesegura/iot-p3
    targetRevision: HEAD
    path: p3_manifests/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
